import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        tertiary: "#000000",
        secondary: "#645d54",
        "tertiary-fixed-dim": "#c7c6c5",
        "secondary-container": "#e9ded2",
        "inverse-primary": "#c8c6c5",
        "on-primary-container": "#858383",
        "surface-variant": "#e4e2e2",
        "on-tertiary": "#ffffff",
        background: "#fbf9f8",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f2f0f0",
        "surface-dim": "#dbdad9",
        "surface-container-lowest": "#ffffff",
        primary: "#000000",
        "primary-fixed-dim": "#c8c6c5",
        outline: "#747878",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#1a1c1b",
        "on-secondary-fixed": "#201b13",
        "on-tertiary-container": "#838482",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#cfc5b9",
        surface: "#fbf9f8",
        "on-background": "#1b1c1c",
        "on-primary-fixed": "#1c1b1b",
        "on-secondary-fixed-variant": "#4c463d",
        "surface-tint": "#5f5e5e",
        "primary-container": "#1c1b1b",
        "on-surface": "#1b1c1c",
        "on-primary-fixed-variant": "#474746",
        "primary-fixed": "#e5e2e1",
        "secondary-fixed": "#ece1d5",
        "tertiary-fixed": "#e3e2e0",
        "surface-container-high": "#e9e8e7",
        "surface-container-low": "#f5f3f3",
        "on-tertiary-fixed-variant": "#464746",
        "inverse-surface": "#303031",
        "tertiary-container": "#1a1c1b",
        "surface-container-highest": "#e4e2e2",
        "surface-bright": "#fbf9f8",
        "on-secondary-container": "#696258",
        error: "#ba1a1a",
        "outline-variant": "#c4c7c7",
        "on-surface-variant": "#444748",
        "error-container": "#ffdad6",
        "surface-container": "#efeded",
        "on-error": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "container-max": "1440px",
        "margin-desktop": "64px",
        gutter: "32px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        headline: ["var(--font-geist)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        "label-caps": ["var(--font-geist)", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-display": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "300" }],
      },
      boxShadow: {
        ambient: "0 4px 24px rgba(0, 0, 0, 0.04)",
        "ambient-lg": "0 8px 30px rgba(0, 0, 0, 0.06)",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};

export default config;
